// ─── SAMPACE EDUCATIONAL LTD — Global Constants ───────────────
// 6-Division Architecture — Revised August 2026

export const BRAND = {
  navy:   "#0B1F3A",
  blue:   "#1565C0",
  sky:    "#42A5F5",
  gold:   "#C9A84C",
  cream:  "#F8F9FF",
  slate:  "#64748B",
  border: "#E2E8F0",
  green:  "#10B981",
  red:    "#EF4444",
  amber:  "#F59E0B",
  purple: "#7C3AED",
  white:  "#ffffff",
  dark:   "#060F1E",
};

export const SITE = {
  name:     "SAMPACE EDUCATIONAL LTD",
  tagline:  "Learn · Empower · Excel",
  motto:    "Excellence Through Education",
  domain:   "sampaceedu.com.ng",
  email:    "info@sampaceedu.com.ng",
  phone:    "+234-800-SAMPACE",
  whatsapp: "https://chat.whatsapp.com/HLWOIKvXhjqIjYAfOFjvTp",
  address:  "Nigeria",
};

export const DIVISIONS = [
  {
    id: "digital", num: "01",
    name: "SAMPACE Digital Campus",
    short: "Online Learning & Digital Skills",
    desc: "SAMPACE's online learning platform for practical digital, professional, technology and language-focused education. Self-paced and instructor-led courses.",
    icon: "💻", color: "#1565C0", g2: "#42A5F5",
    group: "learning",
    groupLabel: "Learning Divisions",
    status: "open",
    btnLabel: "Enroll Now",
    applyType: "student-only",
    tags: ["Digital Skills", "Coding", "AI", "IELTS", "Business", "E-Commerce"],
    programmes: [
      "Computer Fundamentals & Digital Literacy",
      "Microsoft Office Suite (Word, Excel, PowerPoint)",
      "Web Development & Software Development",
      "Data Analysis & Cybersecurity",
      "Graphic Design, UI/UX & Video Editing",
      "Digital Marketing & Social Media",
      "AI Literacy & Prompt Engineering",
      "Entrepreneurship & Business Management",
      "English Language & Communication Skills",
      "IELTS & TOEFL Preparation",
      "French & Other Languages",
      "E-Commerce & Digital Business",
    ],
    highlights: [
      "Self-paced and instructor-led options",
      "Certificate on completion",
      "Online and onsite delivery",
      "Beginner to advanced levels",
    ],
  },
  {
    id: "extramural", num: "02",
    name: "Extramural & Examination Hub",
    short: "Academic Support, Lessons & Exam Preparation",
    desc: "Academic lessons, examination preparation, CBT practice and pre-university programmes for primary, junior secondary, senior secondary and adult learners.",
    icon: "📚", color: "#00897B", g2: "#4DB6AC",
    group: "learning",
    groupLabel: "Learning Divisions",
    status: "open",
    btnLabel: "Enroll Now",
    applyType: "student-only",
    tags: ["WAEC", "NECO", "JAMB", "BECE", "CBT", "Pre-University"],
    programmes: [
      "Primary School Academic Support",
      "Junior Secondary Academic Support (JSS1–JSS3)",
      "Senior Secondary Academic Support (SS1–SS3)",
      "WAEC Examination Preparation",
      "NECO Examination Preparation",
      "JAMB/UTME Preparation",
      "BECE Preparation",
      "GCE & Cambridge Preparation",
      "IELTS & SAT Preparation",
      "Pre-University Academic Lessons",
      "CBT Practice & Computer-Based Mock Exams",
      "Holiday, Weekend & Evening Lessons",
      "Home & Individual Tutoring",
    ],
    highlights: [
      "All major Nigerian examinations covered",
      "Online and physical lessons",
      "Morning, afternoon and evening schedules",
      "Experienced tutors",
    ],
  },
  {
    id: "professional", num: "03",
    name: "Professional Learning Centre",
    short: "Professional Development · Teacher Training · Workplace Skills",
    desc: "Professional development, teacher training, leadership, workplace skills and entrepreneurship programmes for teachers, graduates, professionals and organisations.",
    icon: "🏢", color: "#7B1FA2", g2: "#BA68C8",
    group: "learning",
    groupLabel: "Learning Divisions",
    status: "open",
    btnLabel: "Apply Now",
    applyType: "student-only",
    tags: ["Teacher Training", "CPD", "Leadership", "Workplace Skills", "Entrepreneurship"],
    programmes: [
      "Teacher ICT Training & Digital Teaching Skills",
      "Modern Teaching Methods & Classroom Management",
      "AI for Teachers & Educational Technology",
      "CPD Programmes & Teacher Professional Development",
      "Educational Leadership & School Management",
      "Leadership Development & Strategic Management",
      "Workplace Communication & Customer Service",
      "Office Administration & Business Communication",
      "CV Development & Interview Preparation",
      "Employability & Workplace Readiness Skills",
      "Entrepreneurship & Small Business Management",
      "Financial Literacy & Digital Entrepreneurship",
    ],
    highlights: [
      "For teachers, graduates and professionals",
      "CPD-aligned programmes",
      "Certificate on completion",
      "Corporate and group bookings available",
    ],
  },
  {
    id: "consult", num: "04",
    name: "SAMPACE Consulting",
    short: "Educational, Institutional & Professional Consultancy",
    desc: "Educational consultancy for schools, educational organisations, businesses and institutions. School development, curriculum, EdTech and research consultancy.",
    icon: "🤝", color: "#BF360C", g2: "#FF6D00",
    group: "services",
    groupLabel: "Service Divisions",
    status: "open",
    btnLabel: "Get a Quote",
    applyType: "inquiry",
    tags: ["School Development", "Curriculum", "EdTech Consultancy", "Research", "Training"],
    programmes: [
      "School Development & Improvement Consultancy",
      "Educational Planning & Academic Structure",
      "Curriculum Development & Consultancy",
      "School Policies, Procedures & Administration",
      "Quality Assurance & School Improvement",
      "Educational Technology (EdTech) Consultancy",
      "LMS Selection & Digital Transformation",
      "ICT Planning & Technology Implementation",
      "Research Consultancy & Methodology Support",
      "Institutional Research & Research Capacity Building",
      "Staff Training & Teacher Capacity Building",
      "Corporate Training & Organisational Development",
    ],
    highlights: [
      "For schools, institutions and organisations",
      "Bespoke consultancy packages",
      "Experienced education consultants",
      "Remote and on-site engagements",
    ],
  },
  {
    id: "research", num: "05",
    name: "Research & Digital Services",
    short: "Research Support · Data Services · Computer & Digital Services",
    desc: "Research support, data analysis, project writing assistance, computer centre services, printing, documentation, online services and digital solutions.",
    icon: "🔬", color: "#33691E", g2: "#8BC34A",
    group: "services",
    groupLabel: "Service Divisions",
    status: "open",
    btnLabel: "Get Started",
    applyType: "inquiry",
    tags: ["Research Support", "Data Analysis", "SPSS", "Computer Centre", "Printing", "CVs"],
    programmes: [
      "Research Topic & Proposal Development",
      "Literature Review & Academic Research Support",
      "Questionnaire Design & Data Collection",
      "Data Entry, Coding & Data Cleaning",
      "Excel & SPSS Data Analysis",
      "Research Findings & Report Writing",
      "Project & Thesis Formatting (APA & others)",
      "Academic Proofreading & Editing",
      "Research Methodology & SPSS Training",
      "Computer Access, Typing & Word Processing",
      "Printing, Scanning & Photocopying",
      "CV Preparation & Professional Documentation",
      "Online Applications & Form Assistance",
      "Graphic Design — Flyers, Posters & Social Media Graphics",
    ],
    highlights: [
      "Research assistance, not project completion",
      "Physical computer centre services",
      "Professional document services",
      "Fast turnaround on all print jobs",
    ],
  },
  {
    id: "edtech", num: "06",
    name: "SAMPACE EdTech",
    short: "School Technology & Digital Transformation",
    desc: "Technology solutions helping schools become more connected, efficient and digitally enabled. School websites, LMS implementation, CBT systems and school management technology.",
    icon: "⚡", color: "#4A148C", g2: "#9C27B0",
    group: "services",
    groupLabel: "Service Divisions",
    status: "open",
    btnLabel: "Learn More",
    applyType: "inquiry",
    tags: ["School Websites", "LMS", "CBT Systems", "School Management", "Digital Classrooms"],
    programmes: [
      "School Website Development & Maintenance",
      "Domain, Hosting & School Email Setup",
      "LMS Implementation & Configuration",
      "Digital Classroom Setup & Teacher Training",
      "CBT System Implementation for Schools",
      "Online Examination & Assessment Platforms",
      "Student Information & Admission Systems",
      "Attendance, Results & Fee Management Solutions",
      "Parent & Teacher Communication Systems",
      "School Technology Assessment & ICT Planning",
      "Digital Transformation Strategy & Implementation",
      "Technology Support, Training & Maintenance",
    ],
    highlights: [
      "B2B solutions for schools and institutions",
      "Integration of proven existing technologies",
      "SAMPACE ERP currently in development",
      "Remote and on-site support available",
    ],
  },
];

export const DIVISION_GROUPS = [
  {
    id: "learning",
    label: "Learning Divisions",
    desc: "Enroll in courses, lessons and training programmes",
    color: "#1565C0",
    icon: "🎓",
    ids: ["digital", "extramural", "professional"],
  },
  {
    id: "services",
    label: "Service Divisions",
    desc: "Consultancy, research support and technology solutions",
    color: "#BF360C",
    icon: "🛠️",
    ids: ["consult", "research", "edtech"],
  },
];

export const USER_ROLES = {
  super_admin:        { label:"Super Administrator",      color:"#C9A84C" },
  assistant_admin:    { label:"Assistant Administrator",  color:"#1565C0" },
  digital_admin:      { label:"Digital Campus Admin",     color:"#1565C0" },
  extramural_admin:   { label:"Extramural Admin",         color:"#00897B" },
  professional_admin: { label:"Professional Learning Admin", color:"#7B1FA2" },
  consult_admin:      { label:"Consulting Admin",         color:"#BF360C" },
  research_admin:     { label:"Research & Digital Admin", color:"#33691E" },
  edtech_admin:       { label:"EdTech Admin",             color:"#4A148C" },
  teacher:            { label:"Tutor / Teacher",          color:"#1565C0" },
  student:            { label:"Student / Learner",        color:"#42A5F5" },
  parent:             { label:"Parent / Guardian",        color:"#00897B" },
};

export const STAFF_ROLES = {
  digital:      ["Campus Director","Programme Manager","Course Instructor","Teaching Assistant","Community Manager"],
  extramural:   ["Programme Coordinator","Centre Coordinator","Subject Tutor","CBT Administrator","Instructor","Mentor"],
  professional: ["Director","Lead Facilitator","Lecturer","Trainer","Instructor"],
  consult:      ["Lead Consultant","Educational Consultant","Research Consultant","Project Officer","Trainer"],
  research:     ["Research Coordinator","Research Assistant","Data Analyst","Document Officer","Computer Operator"],
  edtech:       ["Technical Lead","Software Developer","UI/UX Designer","Project Manager","Support Officer"],
};

export const sb    = () => window.__supabase || null;
export const fmt   = n  => "₦" + Number(n || 0).toLocaleString();
export const fmtDate = d => d ? new Date(d).toLocaleDateString("en-NG") : "—";
