// ─── SAMPACE EDUCATIONAL LTD — Global Constants ───────────────
// Single source of truth for all shared values

export const BRAND = {
  navy:    "#0B1F3A",
  blue:    "#1565C0",
  sky:     "#42A5F5",
  gold:    "#C9A84C",
  cream:   "#F8FAFF",
  slate:   "#64748B",
  border:  "#E2E8F0",
  green:   "#10B981",
  red:     "#EF4444",
  amber:   "#F59E0B",
  purple:  "#7C3AED",
  white:   "#ffffff",
  dark:    "#060F1E",
};

export const SITE = {
  name:      "SAMPACE EDUCATIONAL LTD",
  tagline:   "Where Excellence Begins",
  domain:    "sampaceedu.com.ng",
  email:     "info@sampaceedu.com.ng",
  phone:     "+234-800-SAMPACE",
  whatsapp:  "https://chat.whatsapp.com/HLWOIKvXhjqIjYAfOFjvTp",
  address:   "Nigeria",
};

export const DIVISIONS = [
  {
    id: "college", num: "01",
    name: "SAMPACE College",
    short: "Online Secondary School",
    desc: "Full JSS1–SS3 online secondary school. Live classes, virtual labs, CBT exams, digital report cards and parent portals.",
    icon: "🏫", color: "#1565C0", g2: "#42A5F5",
    group: "Academic Education",
    status: "open",
    btnLabel: "Enroll Now",
    applyType: "parent-student",
    tags: ["JSS1–SS3", "Live Classes", "Virtual Labs", "Parent Portal"],
    programmes: ["Junior Secondary (JSS1–JSS3)", "Senior Secondary (SS1–SS3)", "Sciences", "Humanities", "Business"],
  },
  {
    id: "extramural", num: "02",
    name: "Extramural & Exam Hub",
    short: "After-School · Exam Prep · Adult Learning",
    desc: "After-school coaching, WAEC/NECO/JAMB/BECE preparation, adult literacy, holiday lessons and home tutoring.",
    icon: "📚", color: "#00897B", g2: "#4DB6AC",
    group: "Academic Education",
    status: "open",
    btnLabel: "Enroll Now",
    applyType: "student-only",
    tags: ["WAEC", "NECO", "JAMB", "After-School", "Adult Learning"],
    programmes: ["WAEC Coaching", "NECO Coaching", "JAMB/UTME Prep", "BECE Coaching", "Adult Literacy", "After-School Lessons"],
  },
  {
    id: "preuni", num: "03",
    name: "Pre-University Centre",
    short: "IJMB · JUPEB · Foundation Studies",
    desc: "Direct 200-level entry programmes. IJMB, JUPEB, Pre-Degree, Diploma and university admissions coaching.",
    icon: "🏛️", color: "#BF360C", g2: "#FF6D00",
    group: "Academic Education",
    status: "open",
    btnLabel: "Apply Now",
    applyType: "student-only",
    tags: ["IJMB", "JUPEB", "Pre-Degree", "Diploma"],
    programmes: ["IJMB (2-year)", "JUPEB (1-year)", "Pre-Degree", "Foundation Diploma", "Post-UTME Coaching"],
  },
  {
    id: "digital", num: "04",
    name: "Digital Campus",
    short: "Technology · Business · Languages",
    desc: "Six specialist professional schools — Technology, Business, Languages, Communication, International Programmes and Advanced Studies.",
    icon: "💻", color: "#7B1FA2", g2: "#BA68C8",
    group: "Professional & Digital Learning",
    status: "open",
    btnLabel: "Enroll Now",
    applyType: "student-only",
    tags: ["Coding", "IELTS", "French", "PMP", "ACCA", "UI/UX"],
    programmes: ["Full-Stack Web Dev", "Cybersecurity", "Data Science", "IELTS Prep", "French Language", "ACCA", "PMP", "Public Speaking"],
  },
  {
    id: "professional", num: "05",
    name: "Professional Learning Centre",
    short: "Executive · Corporate · CPD",
    desc: "Executive education, teacher development, school leadership, corporate training and continuing professional development.",
    icon: "🏢", color: "#E65100", g2: "#FF6D00",
    group: "Professional & Digital Learning",
    status: "open",
    btnLabel: "Apply Now",
    applyType: "student-only",
    tags: ["CPD", "Corporate Training", "Leadership", "Teacher Dev"],
    programmes: ["Executive Education", "Teacher Development", "School Leadership", "Corporate Training", "CPD Bootcamps"],
  },
  {
    id: "cbt", num: "06",
    name: "CBT Platform",
    short: "Past Questions · Mock Exams · Practice",
    desc: "WAEC, NECO and JAMB past questions 2010–2024. Token-based CBT practice, mock exams, Android and Windows app.",
    icon: "🖥️", color: "#006064", g2: "#00BCD4",
    group: "Professional & Digital Learning",
    status: "open",
    btnLabel: "Get Access",
    applyType: "student-only",
    tags: ["WAEC CBT", "NECO CBT", "JAMB Simulator", "Mock Exams"],
    programmes: ["WAEC Practice", "NECO Practice", "JAMB Practice", "BECE Practice", "Mock Examinations"],
  },
  {
    id: "publish", num: "07",
    name: "SAMPACE Publishing",
    short: "Books · Resources · Digital Content",
    desc: "Educational textbooks, workbooks, e-books, teacher guides, curriculum resources and digital learning content.",
    icon: "📖", color: "#33691E", g2: "#8BC34A",
    group: "Corporate & Knowledge Services",
    status: "open",
    btnLabel: "Explore",
    applyType: "inquiry",
    tags: ["Textbooks", "E-books", "Curriculum", "Digital Content"],
    programmes: ["Educational Textbooks", "Workbooks", "E-books", "Teacher Guides", "Digital Courses"],
  },
  {
    id: "consult", num: "08",
    name: "SAMPACE Consulting",
    short: "School Improvement · Advisory",
    desc: "School establishment support, curriculum development, accreditation guidance and educational policy advisory.",
    icon: "🤝", color: "#4A148C", g2: "#9C27B0",
    group: "Corporate & Knowledge Services",
    status: "open",
    btnLabel: "Get a Quote",
    applyType: "inquiry",
    tags: ["School Setup", "Accreditation", "Curriculum Dev"],
    programmes: ["School Establishment", "Curriculum Development", "Accreditation Support", "Digital Transformation"],
  },
  {
    id: "research", num: "09",
    name: "Research & Innovation",
    short: "Think Tank · Knowledge Hub · Journals",
    desc: "Educational research, innovation hub, AI in education, academic journals and research partnerships.",
    icon: "🔬", color: "#1A237E", g2: "#3F51B5",
    group: "Corporate & Knowledge Services",
    status: "open",
    btnLabel: "Learn More",
    applyType: "inquiry",
    tags: ["Research", "Innovation", "AI in Education", "Journals"],
    programmes: ["Research Partnerships", "Academic Journals", "Innovation Hub", "Think Tank", "Conferences"],
  },
  {
    id: "edtech", num: "10",
    name: "SAMPACE EdTech",
    short: "LMS · School Management · AI Tools",
    desc: "School management systems, AI learning assistant, teacher tools, student analytics and digital infrastructure.",
    icon: "⚡", color: "#006064", g2: "#00BCD4",
    group: "Corporate & Knowledge Services",
    status: "open",
    btnLabel: "Learn More",
    applyType: "inquiry",
    tags: ["LMS", "AI Tools", "School Management", "Analytics"],
    programmes: ["Learning Management System", "School ERP", "AI Learning Assistant", "Teacher Tools"],
  },
  {
    id: "scholarships", num: "11",
    name: "Scholarship Bank",
    short: "Grants · Fellowships · Bursaries",
    desc: "Scholarship database, student sponsorship, fellowship opportunities, education grants and financial aid guidance.",
    icon: "🌟", color: "#F57F17", g2: "#FFC107",
    group: "Community & Opportunity",
    status: "open",
    btnLabel: "Find Scholarships",
    applyType: "inquiry",
    tags: ["Scholarships", "Grants", "Fellowships", "Financial Aid"],
    programmes: ["Undergraduate Scholarships", "Postgraduate Fellowships", "Vocational Grants", "Financial Aid"],
  },
  {
    id: "careers", num: "12",
    name: "SAMPACE Careers",
    short: "Jobs · Recruitment · Internships · Alumni",
    desc: "Graduate recruitment, teacher recruitment, internship programmes, volunteer opportunities and alumni network.",
    icon: "💼", color: "#37474F", g2: "#78909C",
    group: "Community & Opportunity",
    status: "open",
    btnLabel: "Make Enquiry",
    applyType: "inquiry",
    tags: ["Graduate Jobs", "Teacher Jobs", "Internships", "Alumni"],
    programmes: ["Graduate Recruitment", "Teacher Recruitment", "Internships", "Volunteer", "Alumni Network"],
  },
];

export const DIVISION_GROUPS = [
  { id: "academic",      label: "Academic Education",           color: "#1565C0", ids: ["college","extramural","preuni"] },
  { id: "professional",  label: "Professional & Digital Learning", color: "#7B1FA2", ids: ["digital","professional","cbt"] },
  { id: "corporate",     label: "Corporate & Knowledge Services",  color: "#33691E", ids: ["publish","consult","research","edtech"] },
  { id: "community",     label: "Community & Opportunity",      color: "#F57F17", ids: ["scholarships","careers"] },
];

export const USER_ROLES = {
  super_admin:        { label: "Super Administrator",    color: "#C9A84C", access: "all" },
  assistant_admin:    { label: "Assistant Administrator",color: "#1565C0", access: "all_limited" },
  academic_admin:     { label: "Academic Division Admin",color: "#1565C0", access: "academic" },
  professional_admin: { label: "Professional Division Admin", color: "#7B1FA2", access: "professional" },
  college_admin:      { label: "College Administrator",  color: "#1565C0", access: "college" },
  extramural_admin:   { label: "Extramural Administrator",color: "#00897B", access: "extramural" },
  preuni_admin:       { label: "Pre-University Admin",   color: "#BF360C", access: "preuni" },
  digital_admin:      { label: "Digital Campus Admin",   color: "#7B1FA2", access: "digital" },
  cbt_admin:          { label: "CBT Administrator",      color: "#006064", access: "cbt" },
  publish_admin:      { label: "Publishing Administrator",color: "#33691E", access: "publish" },
  teacher:            { label: "Teacher",                color: "#1565C0", access: "own_classes" },
  student:            { label: "Student",                color: "#42A5F5", access: "own_data" },
  parent:             { label: "Parent/Guardian",        color: "#00897B", access: "child_data" },
};

export const sb = () => window.__supabase || null;
export const fmt = n => "₦" + Number(n || 0).toLocaleString();
export const fmtDate = d => d ? new Date(d).toLocaleDateString("en-NG") : "—";
